#!/usr/bin/with-contenv bashio

bashio::log.info "Generating Volkszaehler config.yaml from add-on options"

CONFIG_FILE="/var/www/volkszaehler/etc/config.yaml"

DB_HOST=$(bashio::config 'db_host')
DB_PORT=$(bashio::config 'db_port')
DB_USER=$(bashio::config 'db_user')
DB_PASSWORD=$(bashio::config 'db_password')
DB_NAME=$(bashio::config 'db_name')
DB_ADMIN_USER=$(bashio::config 'db_admin_user')
DB_ADMIN_PASSWORD=$(bashio::config 'db_admin_password')

# Fallback-Defaults, falls etwas leer ist (sollte wegen schema eigentlich nicht passieren)
: "${DB_HOST:=core-mariadb}"
: "${DB_PORT:=3306}"
: "${DB_USER:=vz}"
: "${DB_PASSWORD:=demo}"
: "${DB_NAME:=volkszaehler}"
: "${DB_ADMIN_USER:=vz_admin}"
: "${DB_ADMIN_PASSWORD:=admin_demo}"

cat > "${CONFIG_FILE}" <<EOF
# Automatically generated by Home Assistant add-on

php:
  timezone: Europe/Berlin
  locale: ['de_DE', 'en_US', 'C']

db:
  driver: pdo_mysql
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  charset: utf8
  dbname: ${DB_NAME}
  path: volkszaehler

  admin:
    user: ${DB_ADMIN_USER}
    password: ${DB_ADMIN_PASSWORD}

# push:
#  server: 5582
#  broadcast: 8082
#  wamp:
#    - /
#    - /ws
#  websocket:
#    - /socket

network:
  postlimit: false

debug: false
EOF

bashio::log.info "Volkszaehler config.yaml written to ${CONFIG_FILE}"
